ignores: [
    # Used as a script in package.json
    "http-server",
    "rollup",
    "rimraf",

    # ESLint plugins, which are expected to be installed, even if never specifically referenced
    "eslint-config-prettier",
    "eslint-plugin-jsdoc",

    # Configured with the jest.config.js
    "jest-environment-jsdom",

    # Helper library sideloaded by other things
    "tslib",
    "@types/jest"
  ]
skip-missing: true

# https://github.com/depcheck/depcheck/issues/615
parsers:
  "**/*.mjs":
    - "es6"
  "**/*.cjs":
    - "es6"
  "**/*.mts":
    - "typescript"
  "**/*.cts":
    - "typescript"
  "**/*.jsx":
    - "jsx"
  "**/*.tsx":
    - "typescript"
  "**/*.ts":
    - "typescript"
  "**/*.js":
    - "es6"
